services:
  p2portal:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  relay-server:
    build:
      context: ./relay-server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      - RELAY_PORT=8080
      - RELAY_MAX_TRANSFER_SIZE=104857600
